//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpinteriaProyecto2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string edad { get; set; }
        public string genero { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        [Display(Name = "No. Tarjeta de Credito")]
        [Required(ErrorMessage = "*")]
        [Range(1,9999999999999999, ErrorMessage = "Numero de tarjeta no valida")]
        public Nullable<int> numTarjeta { get; set; }
        [Display(Name = "Mes de Expiracion")]
        [Range(1, 12, ErrorMessage = "Mes no valido")]
        public Nullable<int> tajetaexmes { get; set; }
        [Display(Name = "Year de Expiracion")]
        [Range(2021, 2030, ErrorMessage = "*")]
        public Nullable<int> tarjetexyear { get; set; }
    }
}
