//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstillitaFeliz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int id_comentario { get; set; }
        public string contenido { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_producto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
