//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstillitaFeliz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Compras
    {
        public int id_detallecompras { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<int> id_orden { get; set; }
    
        public virtual Orden_Compra Orden_Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
