//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpinteriaProyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Id_producto { get; set; }
        public string nombre { get; set; }
        public Nullable<double> precio { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string imagen { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> stock { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
